In [5]:

import pandas as pd
data=pd.read_csv('book1.csv')
data
x=data['squarefeet']
y=data['price']
import statsmodels.api as sm
model=sm.OLS(y,x).fit()
model.summary()
data['prediction']=model.predict(x)
data

KeyError: 'squarefeet'

In [3]:
pwd

'D:\\Darvin\\python training'

In [2]:
cd D:\Darvin\python training

D:\Darvin\python training

In [6]:

import pandas as pd
data=pd.read_excel('mlr.xlsx')
data

,sno,Item_Weight,Item_Fat_Content,Item_Visibility,Item_MRP,Item_Outlet_Sales
0,1,19.200,1,0.005620,226.6062,5191.2426
1,2,5.175,1,0.029663,105.2622,2328.9684
2,3,9.800,1,0.045523,35.0874,352.8740
3,4,16.000,1,0.099833,87.4856,263.6568
4,5,7.090,0,0.007256,50.4034,340.2238
...,...,...,...,...,...,...
799,800,15.150,1,0.066551,144.6760,3954.8520
800,801,16.000,1,0.065432,76.1986,1869.5664
801,802,18.750,0,0.034501,211.7218,5770.4886
802,803,12.100,0,0.016922,178.3660,4314.3840
803,804,8.655,1,0.088694,122.5756,2181.1608

In [9]:
x=data.iloc[:,1:5]
y=data.iloc[:,5]
import statsmodels.api as sm
model=sm.OLS(y,x).fit()
model.summary()
y
x

     Item_Weight  Item_Fat_Content  Item_Visibility  Item_MRP
0         19.200                 1         0.005620  226.6062
1          5.175                 1         0.029663  105.2622
2          9.800                 1         0.045523   35.0874
3         16.000                 1         0.099833   87.4856
4          7.090                 0         0.007256   50.4034
..           ...               ...              ...       ...
799       15.150                 1         0.066551  144.6760
800       16.000                 1         0.065432   76.1986
801       18.750                 0         0.034501  211.7218
802       12.100                 0         0.016922  178.3660
803        8.655                 1         0.088694  122.5756

[804 rows x 4 columns]

In [13]:

data['predicted_sales']=model.predict(x)
data

,sno,Item_Weight,Item_Fat_Content,Item_Visibility,Item_MRP,Item_Outlet_Sales,predicted_sales
0,1,19.200,1,0.005620,226.6062,5191.2426,4005.077101
1,2,5.175,1,0.029663,105.2622,2328.9684,1873.318921
2,3,9.800,1,0.045523,35.0874,352.8740,641.259344
3,4,16.000,1,0.099833,87.4856,263.6568,1465.221215
4,5,7.090,0,0.007256,50.4034,340.2238,860.098142
...,...,...,...,...,...,...,...
799,800,15.150,1,0.066551,144.6760,3954.8520,2500.556094
800,801,16.000,1,0.065432,76.1986,1869.5664,1322.020853
801,802,18.750,0,0.034501,211.7218,5770.4886,3603.684575
802,803,12.100,0,0.016922,178.3660,4314.3840,3053.006098
803,804,8.655,1,0.088694,122.5756,2181.1608,2084.632135

In [21]:
import pandas as pd
data=pd.read_csv('binary.csv')
x=data.iloc[:,1:16]
y=data.iloc[:,0]
import statsmodels.api as sm
model=sm.Logit(y, x).fit()
model.summary()

Optimization terminated successfully.
         Current function value: 0.086424
         Iterations 10

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                  class   No. Observations:                  435
Model:                          Logit   Df Residuals:                      420
Method:                           MLE   Df Model:                           14
Date:                Tue, 31 Mar 2020   Pseudo R-squ.:                  0.8704
Time:                        12:19:20   Log-Likelihood:                -37.594
converged:                       True   LL-Null:                       -290.15
Covariance Type:            nonrobust   LLR p-value:                 7.620e-99
==========================================================================================================
                                             coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------------------------
handicapped-infants                        0.6822      0.668      1.021      0.307      -0.627       1.991
water-project                              0.1558      0.739      0.211      0.833      -1.293       1.605
budget-resolution                          3.3384      0.844      3.957      0.000       1.685       4.992
physician-fee-freeze                      -7.8768      1.335     -5.899      0.000     -10.494      -5.259
el-salvador-aid                           -1.8879      1.249     -1.512      0.131      -4.335       0.560
religious-groups                           1.8703      1.192      1.569      0.117      -0.465       4.206
anti-satellite-test-ban                   -0.9467      1.101     -0.860      0.390      -3.105       1.211
aid-to-nicaraguan-contras                  2.7161      1.236      2.197      0.028       0.293       5.139
immigration                               -2.2496      0.864     -2.604      0.009      -3.943      -0.557
synfuels-corporation                       3.7976      0.945      4.020      0.000       1.946       5.649
education-spending                        -1.5448      0.717     -2.153      0.031      -2.951      -0.139
superfund                                  3.0305      1.189      2.549      0.011       0.700       5.361
crime                                      1.2155      0.994      1.223      0.221      -0.732       3.163
duty-free-exports                          1.2013      0.715      1.680      0.093      -0.200       2.602
export-administration-act-south-africa    -1.1539      0.890     -1.297      0.195      -2.898       0.590
==========================================================================================================

Possibly complete quasi-separation: A fraction 0.18 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
"""

In [22]:
data['predicted_value']=model.predict(x)

,class,handicapped-infants,water-project,budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups,anti-satellite-test-ban,aid-to-nicaraguan-contras,immigration,synfuels-corporation,education-spending,superfund,crime,duty-free-exports,export-administration-act-south-africa,predicted_value
0,0,0,1,0,1,1,1,0,0,1,1,1,1,1,0,1,0.009533
1,0,0,1,0,1,1,1,0,0,0,0,1,1,1,0,1,0.002043
2,1,0,1,1,0,1,1,0,0,0,1,0,1,1,0,0,0.999990
3,1,0,1,1,0,1,1,0,0,0,1,0,1,0,0,1,0.999894
4,1,1,1,1,0,1,1,0,0,0,1,1,1,1,1,1,0.999978
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
430,0,0,0,1,1,1,1,0,0,1,0,1,1,1,0,1,0.005177
431,1,0,0,1,0,0,0,1,1,1,0,0,0,0,0,1,0.846087
432,0,0,0,0,1,1,1,0,0,0,1,1,1,1,0,1,0.072457
433,0,0,0,0,1,1,1,1,1,0,0,1,1,1,0,1,0.010173
434,0,0,1,0,1,1,1,0,0,1,0,1,1,1,0,0,0.000684

In [3]:
pwd

'C:\\Users\\Darvin'

In [4]:
cd D:\Darvin\python training

D:\Darvin\python training